name: .NET
env:
  DOTNET_SDK_VERSION: '6.0.100'
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-linux-x64:
    
    runs-on: ubuntu-18.04
    
    steps:
      
      - uses: actions/checkout@v2
      - name: Set up dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: ${{ env.DOTNET_SDK_VERSION }}
          include-prerelease: true
      - run: sudo apt-get update
      - run: sudo apt-get install libcurl4-openssl-dev zlib1g-dev libkrb5-dev
      - run: dotnet publish -r linux-x64 -c Release -o artifact
      - run: strip artifact/BBDown
      
      - name: Upload Artifact[linux-x64]
        uses: actions/upload-artifact@v1.0.0
        with:
          name: BBDown_linux-x64
          path: artifact/BBDown
